image: ruby:2.7

pages:
  stage: deploy
  only:
    - master
  script:
  - mkdir public
  - echo "Installing Java..."
  - apt-get update
  - apt-get -y install default-jdk

  - echo "Creating documentation..."
  - make
  artifacts:
    paths:
    - public
  only:
  - master

